FROM golang:1.9.2

ENV GOPATH=/
ENV PATH=$PATH:/bin

RUN mkdir -p /src/github.com/aditya87/chainstore
ADD . /src/github.com/aditya87/chainstore

WORKDIR /src/github.com/aditya87/chainstore/agent
RUN go build .
WORKDIR /src/github.com/aditya87/chainstore/integration
RUN go build .
WORKDIR /src/github.com/aditya87/chainstore/store
RUN go build .

FROM redis

RUN mkdir -p /app
COPY --from=0 /src/github.com/aditya87/chainstore/agent/agent /app/agent
COPY --from=0 /src/github.com/aditya87/chainstore/store/store /app/store
COPY --from=0 /src/github.com/aditya87/chainstore/integration/integration /app/agent_test

RUN /app/agent_test

